### ISSUE TITLE
`duration-str` does not export its `Result` or `Error` type

### ISSUE THREAD

**Issue by FrancisRussell** [baoyachi/duration-str#11]
I needed to write a wrapper around one of the parse functions to make it play nicely with `clap`'s derive functionality, but I found I could not do this without introducing a dependency on `anyhow` since aliases for the error and result types used aren't available in the crate directly.

**Comment by baoyachi** [comment]
I‘m try refactor `duration-str` Result

**Comment by baoyachi** [comment]
@FrancisRussell  Now, published new version, please use
```toml
[dependencies]
duration-str = "0.5.0"
```
