### ISSUE TITLE
DError is private / isn't re-exported

### ISSUE THREAD

**Issue by SergeyKasmy** [baoyachi/duration-str#54]
After updating from version 0.5 to 0.11.2, I now get an error saying that `duration_str::DError` isn't public. `duration_str::error` isn't public either. `duration_str::DResult` on the other hand is public.

I'm assuming this was either a slip up or a strange intentional change for whatever reason. 

I'm using this type as an enum variant of [my library's error enum](https://github.com/SergeyKasmy/fetcher/blob/baf847ff809c6c9e86c7ded9942b438ef75a8fcd/fetcher-config/src/error.rs#L39).

If this is indeed an unintentional change, I can make a pull request to fix it.

Also, why do some functions return string errors? That's just strange... Should I fix that, too?

**Comment by baoyachi** [comment]
@SergeyKasmy  The reason for `returning string errors ` is to make the parsed error information simple enough and enhance readability

**Comment by SergeyKasmy** [comment]
Thanks!
